### ISSUE TITLE
Printing

### ISSUE THREAD

**Issue by jeanmichelcote** [aldeed/meteor-console-me#1]
Hi, your package is almost what i was looking for.

Because my app has an html div that acts like a console display on which i print every console.log output that comes from the client straight to the page. So i wanted also to be able to print there the logs from the server, that is why i installed your package. But it seems like i would need to insert my own wrapped console.log command called devlog(); into your code, somewhere after line 63 of your console-me.js file.

The thing is that i can't find it anywhere on my local project...

Can you help with this?

**Comment by jeanmichelcote** [comment]
So is there a way to grab the output of console-me and send it to a html div as well as its usual destination, which is the console? I'm trying to tap into the collection with "_clientConsole.find();" but nothing comes out...

**Comment by aldeed** [comment]
Hi, clone this repo into your /packages folder and set your div value after this line: https://github.com/aldeed/meteor-console-me/blob/master/console-me.js#L63
